# Generated by Django 3.2.3 on 2021-06-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=500)),
                ('imagemnoticia', models.ImageField(upload_to='Noticiathumb')),
                ('site', models.CharField(max_length=500)),
            ],
        ),
    ]
