# Generated by Django 3.2.3 on 2021-06-22 22:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_alter_noticia_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(max_length=1024),
        ),
    ]
