# Generated by Django 3.2.3 on 2021-06-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sobre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobre',
            old_name='titulo',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='sobre',
            name='descricao',
            field=models.TextField(max_length=1024),
        ),
    ]
