# Generated by Django 3.2.3 on 2021-06-23 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=3)),
                ('municipio', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('casosAcumulado', models.IntegerField()),
                ('casosNovos', models.IntegerField()),
                ('obitosAcumulado', models.IntegerField()),
                ('obitosNovos', models.IntegerField()),
            ],
        ),
    ]
